canonical: http://hl7.org/fhir/us/pcs
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: hl7.fhir.us.pcs
name: US-PCS
title: United States Patient Care Summary (US-PCS) Implementation Guide
status: active
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: cgp
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 0
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
license: CC0-1.0
version: 1.0.0-ballot
copyrightYear: 2026+
releaseLabel: STU 1
publisher:
  name: HL7 International / Cross-Group Projects
  url: http://www.hl7.org/Special/committees/structure
jurisdiction: 'urn:iso:std:iso:3166#US'
dependencies:
  hl7.fhir.uv.ips:
    version: 2.0.0
    uri: http://hl7.org/fhir/uv/ips/ImplementationGuide/hl7.fhir.uv.ips
  hl7.fhir.us.core:
    version: 6.1.0
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
  hl7.fhir.uv.fhir-clinical-document:
    version: 1.0.1
    uri: http://hl7.org/fhir/uv/fhir-clinical-document/ImplementationGuide/hl7.fhir.uv.fhir-clinical-document
menu:
  Home: index.html
  Table of Contents: toc.html
  Guidance: 
    General Guidance: general-guidance.html
    Terminology Guidance: terminology-guidance.html
    Use Case: use-case.html
    US Variance Statement: us-variance-to-ips.html
  FHIR Artifacts:
    Profiles: profiles.html
    Examples: examples.html
  Support:
    About: IG-analysis.html
    Downloads: downloads.html
    Copyrights: copyrights.html
  Change Log: changes.html